apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-demo-component-kizt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-demo-component-kizt
    app.kubernetes.io/part-of: mvp-test-app
  name: rhtap-demo-component-kizti5sh
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhtap-demo-component-kizt
    weight: 100
status: {}
